#!/usr/bin/env python3

"""Generate the worklist for submitting a bunch of jobs that compute MD5s.
Execute "submit-md5-jobs worklist_file_path" to then submit all the jobs."""

import argparse
from functools import partial
import logging
import sys

import wh_lib


logger = logging.getLogger(__name__)


def main():
    args = parse_args()
    config_logging(args)
    run(args)
    logging.shutdown()


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('worklist_file_path')
    parser.add_argument('-v', '--verbose', action='store_true')
    args = parser.parse_args()
    return args


def config_logging(args):
    global logger
    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(level=level)
    logger = logging.getLogger('gen-topmed-md5')


def run(args):
    logger.debug('args: %r', args)
    worklist = wh_lib.parse_excel_records(args.worklist_file_path)
    batch_dir, project_dir = extract_batch_info(worklist)
    worklist_name = '{}_md5'.format(batch_dir)
    new_dir = '{0}/{1}'.format(project_dir, batch_dir)
    with open(worklist_name, 'w') as fout:
        output_copy_script(fout, new_dir, worklist)


def extract_batch_info(worklist):
    """Return batch_dir & project_dir, which must be the same for all rows."""
    batch_dirs = set(r.batch for r in worklist)
    project_dirs = set(r.hgsc_xfer_subdir for r in worklist)
    assert len(batch_dirs) == 1, (
        'batch must be the same for all BAMs in worklist'
    )
    assert len(project_dirs) == 1, (
        'hgsc_xfer_subdir must be the same for all BAMs in worklist'
    )
    batch_dir = list(batch_dirs)[0]
    project_dir = list(project_dirs)[0]
    return batch_dir, project_dir


def output_copy_script(fout, new_dir, worklist):
    pr = partial(print, file=fout)
    for r in worklist:
        pr("msub-md5 '{}' '{}'".format(r.new_bam_name, r.bam_path))


if __name__ == '__main__':
    main()
